# Generated by Django 4.2.7 on 2023-12-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
