# Generated by Django 4.2.7 on 2023-12-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_item_likes_item_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='likes',
            new_name='num_ratings',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='ratings',
            new_name='total_ratings',
        ),
    ]
