# Generated by Django 4.2.7 on 2023-12-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_likes_item_num_ratings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='num_ratings',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='total_ratings',
            new_name='ratings',
        ),
    ]
