# Generated by Django 4.2.7 on 2023-12-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_num_ratings_item_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='likes',
        ),
    ]
