# Generated by Django 4.2.7 on 2023-12-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='item',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
