# Generated by Django 4.2.7 on 2023-12-04 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0015_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('item', 'user')},
        ),
    ]
